### ISSUE TITLE
Optional map field depending on anothers field value

### ISSUE THREAD

**Issue by IlkoMichler** [cscan/vue-excel-editor#102]
On Issue #80 you suggested:
`<vue-excel-column field="MARA_MATKL" label="..." type="map" :options="optionsDict" width="120px"/>`
with
`optionsDict () {
   if (this.checkItem(this.$refs))
      return this.myBGR002_dict
   else
      return {}
}`

Now in the suggested function "this.checkItem(this.$refs)" i have to decide upon the value of another cell in the same row what the select or map should deliver. I have troubles to address the neighboring cell to check the value.

Could you please give me a hint how to access it?
Since I will have to update the select/map, if the value of the depending fiend changes the value:
 At what time is the select or map set up? Is it at mount or when clicking the selection symbol (down arrow) in the cell? 

Thanks!
I wish you the best!

Cheers Ilko

**Comment by cscan** [comment]
As I remember, the options function can return a promise. You could update myBGR002_dict before return to the call

**Comment by IlkoMichler** [comment]
Promise will not help too much.  I need to access the value of another column (say Column1) of the same row data to make a decision, which selection set to present in the very column (say Column2).
How o I access that value to make my decision.
If the call for a map is done on clicking the field Column 2 I can at that time read the value form Column 1 and decide, which selection to present. If it would be calculated and cached in mount, I would need to have addition on value change in Column 1 to update the selection in Column 2 - which comes close to a promise.

Sorry for me expressing so badly what I would need.

**Comment by cscan** [comment]
According to the code: 
```js
            if (field.options.constructor.name.endsWith('Function')) {
              list = await field.options(value, this.currentRecord)
              if (field.type === 'map') list = Object.values(list)
              else list = list.slice()
              if (this.inputBoxShow)
                list = list.filter(element => element.toUpperCase().includes(value))
              list.sort().splice(listCount)
              // this.autocompleteSelect = list.findIndex(element => element.toUpperCase().includes(value))
            }
```

this shows that if the component detects the options is an function, it will call it by passing 2 arguments (value, record). You may try to print out the arguments in your promise function to see what happened. Something like this:

```js
optionsDict (value, record) {
   console.log(value, record)
   return {}
}
```
