### ISSUE TITLE
Validation parameters

### ISSUE THREAD

**Issue by joelbudu** [cscan/vue-excel-editor#11]
Is it possible to gain more context on the cell being validated? Currently, I know you can access the value but are you able to know which cell is being validated and further use this to implement a validation based on other values in the sheet?

**Comment by cscan** [comment]
The validate currently accepts only the new content. Will put more arguments in next version.

If the validation text is not necessary, you may use change prop which provides more arguments (newVal, oldVal, row, field) and allow you to cancel the change event.

**Comment by cscan** [comment]
Added in v1.3.71

**Comment by joelbudu** [comment]
Thanks for the addition. That was a life saver
