### ISSUE TITLE
remember the filter

### ISSUE THREAD

**Issue by capricorn05** [cscan/vue-excel-editor#110]
Hi,
This is a great piece of work.  I was wondering if there is a way to store the filter and reapply from when a user return to the page?

**Comment by capricorn05** [comment]
Hi,
Just wondering if you had a chance to look at this?
Thanks

**Comment by cscan** [comment]
Let me look into that if I have time

**Comment by cscan** [comment]
Hi, you may get and store the hash variable columnFilter. It may auto-refresh once you restore it.
