### ISSUE TITLE
Can't Compaile on wabpack or laravel-mix

### ISSUE THREAD

**Issue by yuan8** [cscan/vue-excel-editor#112]
```
window.Vue = require('vue').default;
import VueExcelEditor from "vue-excel-editor";
Vue.use(VueExcelEditor);
```
i dont know what happen, somebody can explained?
this my result terminal 
<img width="696" alt="Screen Shot 2022-03-28 at 21 34 35" src="https://user-images.githubusercontent.com/9335377/160421905-345868e2-7727-4b38-823c-574de4f77d51.png">

**Comment by yuan8** [comment]
i have reference  about that problem.

https://eslint.vuejs.org/rules/no-v-for-template-key-on-child.html

**Comment by cscan** [comment]
The Index key problem will also talk about in Vue3 compatibility. You may take a look on a contributor's work who written a great Vue3 component for us. 

https://github.com/edutucci/quasar-vue-excel-editor
