### ISSUE TITLE
How do i get the rows? 

### ISSUE THREAD

**Issue by p0sidonz** [cscan/vue-excel-editor#115]
I have a simple jsondata file which i am showing, I have to sum every rows horizontally. But how do i get the each object so that i can add my logic to the 'TOTAL' column for each rows?
![total](https://user-images.githubusercontent.com/20871159/167253842-42102ad6-3137-4d50-bb5f-19868d626dd2.PNG)

**Comment by cscan** [comment]
You may try this alternative way to define the jsondata:

```
data () {
   return {
      jsondata: [{
         employeeId: 123,
         name: 'John wick',
         daysWorked: 30
         perDayWages: 3000,
         get total () {
            return this.daysWorked * this.perDayWages
         }
      }, {
         employeeId: 124,
         name: 'kratos',
         daysWorked: 15
         perDayWages: 3000,
         get total () {
            return this.daysWorked * this.perDayWages
         }
      }]
   }
}
```

**Comment by p0sidonz** [comment]
Oh! Never thought of doing this. Thank you very much! <3
