### ISSUE TITLE
Filtering can not multi select

### ISSUE THREAD

**Issue by tho-actrecipe** [cscan/vue-excel-editor#118]
I tried to select multi value for filtering but impossible.
The modal immediately close after choosing 1 value. 

![multi-select](https://user-images.githubusercontent.com/59632173/177734862-21d9cbcc-2602-4c18-8eb4-935395f8f442.jpg)

**Comment by cscan** [comment]
Yes, select one only. If you want to select multiple, try the regular expression, such as ~0932|0974

**Comment by tho-actrecipe** [comment]
@cscan Can we make it multi select in form? I think it will be more user-friendly.
