### ISSUE TITLE
Display the table in a CSV format without exporting it 

### ISSUE THREAD

**Issue by rac021** [cscan/vue-excel-editor#126]
Hi,

I there a way to display the table in a CSV format without exporting it ?

I found the following method but it exports the results in file

```
 this.$refs.grid.exportTable(format, exportSelectedOnly, filename)

```

Thanks

**Comment by rac021** [comment]
?

**Comment by cscan** [comment]
Rather to use exportTable function, you could write your own function to handle it. Export to csv is rather easy. It can be done by several lines of codes to serializing your data array and write to file. For your reference: https://stackoverflow.com/questions/14964035/how-to-export-javascript-array-info-to-csv-on-client-side
