### ISSUE TITLE
Scroll up/down issue from 1.4

### ISSUE THREAD

**Issue by Helaers** [cscan/vue-excel-editor#134]
I'm having scroll issues on both Mac and Windows when upgrading to `1.4` or above. 
Scrolling left/right works fine (with trackpad), up/down (with trackpad or mouse) doesn't.

Sometimes it starts working (up/down) when I leave the tab open for 5min and revisit it.

My current setup is something like:
```html
<div class="wrapper">
    <excel-editor
      ref="editor"
      :data="employees"
      // other props
      @nextPage="nextPage"
      @previousPage="previousPage"
      @update="updateCell"
    >
       <vue-excel-column field="displayName" :label="$t('global.displayName')" sticky readonly />
       // other columns
    </excel-editor>
<div>
```

```css
.wrapper :deep(.table-content) {
  max-height: calc(100vh - 356px);
}
```

The `:deep` is needed to remove the browsers scrollbar. Given the fact that `v1.4` only has some js changes, I doubt that overwriting the css is the culprit.

**Rolling back to `1.3.95`, it works fine again**.

**Comment by cscan** [comment]
Push the new version 1.5.20. You could set the prop :wheelSensitivity = "1" for better experiences in Mac

**Comment by Helaers** [comment]
Thanks for the quick reply but unfortunately, after bumping to 1.5.20, adding the `wheelSensitivity` prop and setting it to several values, it still doesn't fix the scrolling issue.
