### ISSUE TITLE
Can we use placeholders in each shell?

### ISSUE THREAD

**Issue by JuKyYoon** [cscan/vue-excel-editor#139]
![image](https://github.com/cscan/vue-excel-editor/assets/22341159/6db8fe70-f617-40c4-b13f-75535dd3101b)

I used this editor for data entry purposes.  So i'm making good use of features like validation. 

To use validation, I think I need a feature that informs us of what values need to be entered. Therefore, I checked to see if i could set placeholders in each shell, but unfortunately, I couldn't find such a feature. Is there a similar feature to placeholders, or if i need to implement placeholders ourselves, how should i create it?"

**Comment by cscan** [comment]
There is no exact placeholder feature take place in cell level. But you may try using :validation to return the hint after user typed

**Comment by JuKyYoon** [comment]
I found a solution to add a placeholder using CSS.

```
.vue-excel-editor tr td:nth-child(3):empty::before {
  content: 'placeholder';
  color: #d8d8d8;
}
```

The number 3 is column number.
