### ISSUE TITLE
Not able to change header style

### ISSUE THREAD

**Issue by gmaragao** [cscan/vue-excel-editor#15]
Hello,
first of all I wanna thank you for your effort building this library, it's really awesome.

1) My question/issue is that I'm not being able to change the header class in an 'easy' way, for the future changes in the package I'd suggest a more straightforward way to change the style/classes just like a prop, using a css/scss style. Like other frameworks do.
e.g.: `:custom-class="my-class"`

2) The styles are being rendered with '!important'  value, this could bring a lot of problems when manipulating the style.

![package](https://user-images.githubusercontent.com/39383583/86353736-a4249f80-bc5f-11ea-9f24-5db4659cf560.png)

**Comment by cscan** [comment]
1. Will make it in future release
2. Removed the important clause. Try 1.3.75

**Comment by gmaragao** [comment]
Thanks for the fast response.
