### ISSUE TITLE
Support for different Date format for date column type

### ISSUE THREAD

**Issue by kaushik-xs** [cscan/vue-excel-editor#16]
Currently the date column type supports only `yyyy-mm-dd`. Is there a way to support other date formats (`mm-dd-yyyy` or `dd-mm-yyyy`)?

**Comment by cscan** [comment]
No easy way to do this, but you may customize the conversion between showing text and value by providing toText and toValue function.

**Comment by kaushik-xs** [comment]
@cscan This is cool. I didn't know that there is such an option. Let me try it (toValue and toText) out and get back

**Comment by kaushik-xs** [comment]
This worked. 

```
convertDateToText(value) {
    return moment(value, 'YYYY/MM/DD').format('MM/DD/YYYY')
},
convertDateToValue(text) {
    return moment(text, 'MM/DD/YYYY').format('YYYY/MM/DD')      
}
```

One more point to note, only if the date format is in yyyy/mm/dd the sorting of the column works.

**Comment by cscan** [comment]
Great! I close this ticket then

Yes, the sorting now only treats the date string as text
