### ISSUE TITLE
Pressing tab need to take the cursor to the next row first cell

### ISSUE THREAD

**Issue by kaushik-xs** [cscan/vue-excel-editor#17]
Currently on pressing tab, the cursor only to the next cell. Is there a way to take it to the next row first cell when the cursor reaches the end of the row?

If there is an event with which I can control the tab behaviour, I will also be able to handle the cases to insert new row when there are no more rows after the last cell.

**Comment by cscan** [comment]
Now it can move to next row.

For the behaviour about inserting new row, I will consider it in next release. My idea is introducing a prop "newIfReachBottom" so that if the focusing cell move to bottom, component will add a new record at the end

**Comment by kaushik-xs** [comment]
I did a work around for this. 

Used `vue-shortkey` package and override the default `tab` shortcut key. 

Used the `currentRowPos` and `currentColPos` and manually used `moveTo` to make it move to the first cell of the next row and even create a row. Also used the same to implement `shift+tab` to go to the previous cell.  

@cscan I am not sure if this enhancement is even required, probably we could just mention it in the `README.md` on how to handle custom shortcut and use the default method list that you have provided. 

Let me know what you think.

**Comment by cscan** [comment]
Good to hear that you find a solution. Anyway, please update and try v1.3.76. It added new-if-bottom prop.

Now the key handling is quite complicated. All condition now handle in winKeyDown and it makes the codes quite "messy" indeed. Actually it is easy to provide custom handling and skip all my codes, but most of the features will be affected and not function properly I believe.

Anyway, thanks for your suggestion. I will mention more in readme ...

**Comment by cscan** [comment]
Shift-tab is already have, I think you version is quite old. Please update to latest.

**Comment by kaushik-xs** [comment]
@cscan yes. It is working thanks. 

But the latest version (1.3.76), the enter keypress behaviour has changed. As per the Google sheets, it will shift the focus to the cell below. It behaves like tab now. Was this intended?
