### ISSUE TITLE
Add spellcheck attribute to each cell in the excel

### ISSUE THREAD

**Issue by kaushik-xs** [cscan/vue-excel-editor#19]
I am attempting to add a spellcheck attribute (provided by html) to the cells in the excel. Do you have a suggestion on how or way to achieve this?

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_global_spellcheck

Something like this would help

```
<vue-excel-column spellcheck="true" />
```

**Comment by cscan** [comment]
Will implement a prop in next release

**Comment by cscan** [comment]
Please try v1.3.76

**Comment by kaushik-xs** [comment]
@cscan This works. Thanks for the quick enhancement.
