### ISSUE TITLE
Excel Import writing to a single row

### ISSUE THREAD

**Issue by joelbudu** [cscan/vue-excel-editor#2]
Hi @cscan ,

First of all thanks for working on this extremely powerful tool. 
However, when I attempt to run an excel import only the last cell appears in the table, a little debugging reveals the library must be writing all the rows to a single row, effectively overwriting the contents of the row.

Or maybe I'm doing something wrong

**Comment by cscan** [comment]
Can you show me the codes and Excel? My test has no problem.
The library writes into the grid row by row, by checking the key column.

**Comment by joelbudu** [comment]
So my code looks something like this. And I have attached the excel I'm trying to import

         <template>
            <vue-excel-editor v-model="jsondata" @update="importFunc">
              <vue-excel-column field="property"   label="property" />
              <vue-excel-column field="description"   label="description" />
              <vue-excel-column field="key"  label="key" />
              <vue-excel-column field="value" label="value" />
              <vue-excel-column field="country"    label="country" />
              <vue-excel-column field="data_type"  label="data type" :options="['string','integer','boolean', 'array']" />
              <vue-excel-column field="permissions"  label="permissions" />
              <vue-excel-column field="sortLevel"  label="sortLevel" />
            </vue-excel-editor>
          </template>


[Remote Config Template - Sheet1.xlsx](https://github.com/cscan/vue-excel-editor/files/4573738/Remote.Config.Template.-.Sheet1.xlsx)

**Comment by cscan** [comment]
I suspect the 3rd column "key" field is the root cause. The name is reserved and I use it for special purpose. Try rename to another. Sorry I didn't mention in the document. It is perfect if you code in this way:
```
<template>
 <vue-excel-editor v-model="jsondata" @update="importFunc">
   <vue-excel-column field="property"   label="property" />
   <vue-excel-column field="description"   label="description" />
   <vue-excel-column field="mykey"  label="key" key-field />
   <vue-excel-column field="value" label="value" />
   <vue-excel-column field="country"    label="country" />
   <vue-excel-column field="data_type"  label="data type" :options="['string','integer','boolean', 'array']" />
   <vue-excel-column field="permissions"  label="permissions" />
   <vue-excel-column field="sortLevel"  label="sortLevel" />
 </vue-excel-editor>
</template>
```

**Comment by joelbudu** [comment]
Okay adding the key-field param seems to have done the trick. I've renamed the column completely to "name" to avoid confusion.
Thanks for the support.
