### ISSUE TITLE
Is there any Method to focus on a cell?

### ISSUE THREAD

**Issue by kaushik-xs** [cscan/vue-excel-editor#20]
I am trying to achieve the google sheet behaviour of using enter key.

Steps - Assume a cell is currently chosen in first row

1. User presses enter key and it focuses (cursor) on the text area of the cell
2. Again the presses the enter key, the cell below is shown as active cell
3. Again presses enter key, focuses (cursor) on the text area of the active cell. 

In order to achieve this I am looking for a method to focus so that I can override the enter key behaviour. 

Though of using a combination of `moveSouth` method and focus method, but couldn't find it. 

Please try it out in a google sheet if the above is not clear.

**Comment by cscan** [comment]
If you want to show the cursor within the edit region, you may try to simulate a focus event. Here is the code you could reference:

this.$refs.yourReference.focused = true; 
this.$refs.yourReference.inputBoxShow = 1;
this.$refs.yourReference.$refs.inputBox.focus();

**Comment by kaushik-xs** [comment]
@cscan Thanks. I will try it out and update.
