### ISSUE TITLE
Implementing in Nuxt typescript project

### ISSUE THREAD

**Issue by WTM-Jarryd** [cscan/vue-excel-editor#21]
Hello,

This is not an issue but more a bit of information that may assist those wanting to add this plugin into a Nuxt typescript project or any Vue typescript project.

There are a few things that are required in order to get module resolution working for the plugin.

Firstly a module declaration file is needed. You can add this anywhere inside of your project file structure,
remember the path to where you store this file as it will need to be added to the tsconfig.json file.

###### The following is required for any Vue typescript project, also required for Nuxt projects.
Install the plugin normally via npm or yarn: `npm i vue-excel-editor` or `yarn add vue-excel-editor`

Below is an archive with the module declaration file:
[vue-excel-editor.d.ts.zip](https://github.com/cscan/vue-excel-editor/files/4897168/vue-excel-editor.d.ts.zip)
Add this file to the root of your project directory or into a folder of your choosing.
Alternatively create the `vue-excel-editor.d.ts` file yourself and add the following contents:
```javascript
declare module 'vue-excel-editor';
```

In the tsconfig.json file, in the "include": [ ] field add the path to the above declaration file.
E.g. `"include": ["types/vue-excel-editor.d.ts"]`
The above d.ts file is located in a types folder within the project directory.

This will resolve the issue of the module declaration not being found.

Additionally to resolve the VueExcelEditor component methods, the following will be required:

Using the Options API (i.e. Vue.extend({ })):
I am using the newRecord() example.
```javascript
<script lang="ts>
import Vue, { VueConstructor } from 'vue';
import VueExcelEditor from 'vue-excel-editor';

export default (Vue as VueConstructor<
  Vue & {
    $refs: {
      grid: InstanceType<typeof VueExcelEditor>
    }
  }
>).extend({
  methods: {
    newRecord() {
      // type and interface as per your needs
      const rec = { };

      this.$refs.grid.newRecord(rec);
    }
  }
});
</script>
```

This will allow the resolution of the `this.$refs.grid.newRecord(rec);` method by typing the grid ref.
Change 'grid' to match your required Vue element reference name.

Alternatively, Class API:
```javascript
export default class AppGrid extends Vue {
  $refs: {
    grid: InstanceType<typeof VueExcelEditor>
  },

  methods: {
    ...
  }
}
```

The `grid: InstanceType<typeof VueExcelEditor>` can be shortened to `grid: VueExcelEditor` but it is better to be verbose sometimes.

###### The following is needed specifically for a Nuxt typescript project.

According to the Nuxt documentation on Vue plugins - https://nuxtjs.org/guide/plugins#vue-plugins
the plugin must be added to the project via its own js file and added to the `nuxt.config.js` "plugins" section.

[vue-excel-editor.js.zip](https://github.com/cscan/vue-excel-editor/files/4897294/vue-excel-editor.zip)
Extract the above file to the plugins folder inside your Nuxt project directory.
Alternatively create the `vue-excel-editor.js` file yourself inside the plugins folder (it must be in this folder for Nuxt to detect it correctly) and add the following code:
```javascript
import Vue from 'vue';
import VueExcelEditor from 'vue-excel-editor';

Vue.use(VueExcelEditor);
```
You will not need to add the above code into any of the Vue SFC's where the editor is used.

In the `nuxt.config.js` file add the following to the `plugins: [ ]` field.
**Take note of the mode value. This is important as the plugin does not work with server side rendering and refreshing the app page will result in the following error: `syntax error: Cannot use import outside of module`.**
```javascript
plugins: [{ src: '@/plugins/vue-excel-editor.js', mode: 'client' }],
```

With all of the above, you should have an implemented and compiler error free vue-excel-editor plugin for your Vue or Nuxt typescript project.

I hope it helps.

Jarryd :wave::smiley:

**Comment by cscan** [comment]
Thanks for your suggest. I will consider.
