### ISSUE TITLE
Is there a way to get the row and column identifier of a cell?

### ISSUE THREAD

**Issue by gmaragao** [cscan/vue-excel-editor#25]
Hello,
I was not able to find any way to get the cell identifier according to the row and column.

I wanted to know the column and row of the cell I'm selecting, if the library already has this feature, please, let me know.

**Comment by cscan** [comment]
Did you read the readme about the @select event?

```html
<template>
    <vue-excel-editor v-model="jsondata" @select="onSelect">
    ...
    </vue-excel-editor>
</template>
```

```js
methods: {
    onSelect (selectedRows) {
      console.log(selectedRows)
    }
}
```

It could show the selected row IDs once you select the rows.

For the columns, there is no identifier. But you may locate it by name, by pos or label you provided. It stores in "fields" array variable.

**Comment by gmaragao** [comment]
My question was related to both row and column on the cell. I’ve sent a PR to have these.

The problem is that I need to know when I click on a cell to which row (this one is already provided by the event you mentioned) and column it is related to.

Thanks.

**Comment by cscan** [comment]
You may watch two variables: currentRowPos and currentColPos

在 2020年7月17日 週五 10:54，Gabriel Aragão <notifications@github.com> 寫道：

**Comment by cscan** [comment]
merge your sources and add the events you need. Thanks for your PR. Case closed

**Comment by gmaragao** [comment]
Sure, you're welcome. If I find something else, I'll try to send more PRs, glad to help the lib. 
Also, I think we should update the readme with the new props.

**Comment by cscan** [comment]
Updated. Thanks.
