### ISSUE TITLE
Mandatory property

### ISSUE THREAD

**Issue by joelbudu** [cscan/vue-excel-editor#3]
According to the documentation, the mandatory prop is a string however in the code the mandatory prop is defined as a Boolean, 

    mandatory: {type: Boolean, default: false},

This causes aa warning in the Vue console.

**Comment by cscan** [comment]
Thanks, will update it accordingly

**Comment by joelbudu** [comment]
I thought you will rather change the prop type to String because you are adding the mandatory text to the error list...
```

 if (field.mandatory && content === '')
          transaction.err += (transaction.err ? '\n' : '') + field.mandatory
```

**Comment by cscan** [comment]
Yes, you are right. Changed
