### ISSUE TITLE
Cannot read property 'selectedCount' of undefined

### ISSUE THREAD

**Issue by Akhilskt** [cscan/vue-excel-editor#30]
When i am using **this.$refs.grid.selectedCount** n the computed property it is throwing  _Cannot read property 'selectedCount' of undefined error_.

i have added ref="grid" to <vue-excel-editor only.

My template:
<vue-excel-editor
            ref="grid"
            v-model="defaultJson"
            :no-header-edit="false"
            :allow-add-col="true"
            :add-column="column"
            @select="onSelect"
>

and in script
computed: {
    showActionContainer () {
                return this.$refs.grid.selectedCount > 0  
    },
  }

i am using showActionContainer to display action buttons. but doing this we are getting this error

**Comment by cscan** [comment]
I believe $refs is empty before mounted, you may try this:
```js
showActionContainer () {
   if (this.$refs.grid) return this.$refs.grid.selectedCount > 0
   else return false
}

**Comment by Akhilskt** [comment]
I did try that. In that case, it would be always false even though when i select any row

**Comment by cscan** [comment]
I suggest you console.log( this.$refs.grid.selectedCount ) in setInterval routine for debugging

**Comment by Akhilskt** [comment]
No, I don't think so... I tried with breakpoint.. created methods is not getting triggered after selecting/ unslecting row in that case. $refs are not reactive it seems so once set to false it might not get updated even though i select.

Is there any other way around to check whether the row is selected or not. I have tried @select event but while unselecting it emits two values. so difficult to dechiper from it. How can i achieve this?

**Comment by cscan** [comment]
Strange. I used the selectedCount property in computed methods for thousand times from day one without any problem. What is your debugging result? Can you show me your button html?

Anyway, I remember @select event emit 2 arguments, the 2nd argument shows it is select/unselect.

**Comment by dj12djdjs** [comment]
I'm having the same issue. this.$refs.grid is undefined in any computed variable. But it is available on the mounted hook.
using vue 2.6.12

**Comment by dj12djdjs** [comment]
The only way I was able to solve this was to initialize a data observable to undefined. Then set it to the component in mounted hook.

```
export default {
  name: 'App',
  data () {
     return {
        grid: undefined
     }
   },
  computed: {
     showDelete () {
        return this.grid.selectedCount > 0
     }
   },
   mounted () {
         this.grid = this.$refs.grid
   }
}
```

**Comment by cscan** [comment]
I believe this is because of the Vue lifecycle. The computed is running earlier than mounted. Why not you directly use this.$refs.grid in computed?
