### ISSUE TITLE
Drag copy function

### ISSUE THREAD

**Issue by skyzfdance** [cscan/vue-excel-editor#32]
Sorry, my english is not very good。
I don’t know if the current component can realize the drag copy function，Similar to google Excel.

**Comment by skyzfdance** [comment]
http://oss.skyoc.cn/carens/20200803163528.gif

**Comment by cscan** [comment]
No drag-drop / drag-down in this moment. The copy function is also very limited compare to Excel. ^^"
You could type in Chinese

**Comment by cscan** [comment]
You could type in Chinese

**Comment by skyzfdance** [comment]
哦哦，明白，不好意思，英文确实不怎么好。
那我自己去尝试着实现一下这个功能，麻烦您了。

**Comment by cscan** [comment]
You could make it, I recommend you create PR for us. Thanks.
