### ISSUE TITLE
Limit Moment locales in the build

### ISSUE THREAD

**Issue by RicLeP** [cscan/vue-excel-editor#34]
Is it possible to limit the Moment locales outputted in the final build to reduce the package size?

**Comment by cscan** [comment]
Good idea!!!
How can I do that? Can you process a PR for this?

**Comment by HowdyChad** [comment]
Looks like this is what is needed:
https://github.com/moment/momentjs.com/blob/master/docs/moment/00-use-it/08-webpack.md

**Comment by ste-gr** [comment]
Maybe replace moment with [date-format-parse](https://github.com/mengxiong10/date-format-parse) which is used by [vue2-datepicker](https://github.com/mengxiong10/vue2-datepicker). I think, there should be only some few changes at [VueExcelColumn.vue](src/VueExcelColumn.vue).

**Comment by cscan** [comment]
I have removed the moment dependency.
