### ISSUE TITLE
Focus and copy/paste on column

### ISSUE THREAD

**Issue by yaliya** [cscan/vue-excel-editor#35]
This is a great package. It saved me lots of time. I know its in early stages but one thing that im missing right now is ability to copy an entire column from excel and paste it on the editor. Is this possible yet or in planned ? Thanks

**Comment by cscan** [comment]
Yes, I will plan this in next phase.

**Comment by agentaswin** [comment]
Any update on this feature ? 
TIA

**Comment by kio-by** [comment]
This is a very useful feature. When already? thx
