### ISSUE TITLE
key-field column value must be string?

### ISSUE THREAD

**Issue by ken-mills** [cscan/vue-excel-editor#36]
Please forgive me if there is a better place to ask this question. If so, please advise because I have another non-related question.

When setting key-field=true on column that contains an integer, I get the following error in console when data is loaded:
```
[Vue warn]: Error in render: "TypeError: val.startsWith is not a function"

found in

---> <VueExcelEditor> at node_modules/vue-excel-editor/src/VueExcelEditor.vue
```

This happens regardless of setting the "type" prop on the column. If I cast the value in the json data to a string, it works. I am then able to get key in keys array in the OnUpdate event.  My goal is to get a numeric key back in the keys array OnUpdate.
Is this intended behavior? 
Thank you, Ken

**Comment by cscan** [comment]
I remember the keys will be joined in somewhere so they must be strings. I forget I added the toString() or not. Let me do it in next update. Thanks for your report.

**Comment by ken-mills** [comment]
I found the offending line (VueExcelColumn.vue (72) but ran into an issue testing the fix in my environment. Not sure if this is an appropriate fix or if other changes are necessary.

`if (this.keyField && val && val.startsWith('§')) return ''`

to

`if (this.keyField && val && (typeof val === 'string') && val.startsWith('§')) return ''`

**Comment by cscan** [comment]
This is fixed in v.1.3.80

**Comment by ken-mills** [comment]
Tested. Works great. Thank you.
