### ISSUE TITLE
New Features?

### ISSUE THREAD

**Issue by kas84** [cscan/vue-excel-editor#37]
Hi would it be possible to add some of these features?
1. Custom row title instead of just row number.
2. Regular scroll. Would it be possible to use a Virtual Scroll instead and just  have a normal scroll instead of div?
3. Transform entered text so that for example you can type in lowercase but still have it transformed as uppercase.
4. Select multiple cells with shift key.
5.  Select multiple cells just by dragging down
6. Validate on selects. If you type something that's not in the options, shouldn't it should clear the value?

**Comment by cscan** [comment]
Thanks for your question. Actually we have some of them but not in a single-finger effort:

1. You could provide record-label function to achieve, detail pls see the readme
2. If you specified no-paging, and provide the height, it will have regular vertical scroll bar. Slow performance if rows > 100
3. Does the text-transform prop address your need?
4. Very sorry that currently only support row and single-cell selection.
5. Same as 4.
6. Validation can be done by many ways, please read the readme
