### ISSUE TITLE
How to reset the column-labels for new values?

### ISSUE THREAD

**Issue by egwald** [cscan/vue-excel-editor#40]
How to reset the column-labels for new values?
I use the exel-editor with different numbers of columns, but the labels will be appended.
The changed data are from db-requests on different tables.

**Comment by cscan** [comment]
You may try header-label prop:

```html
<vue-excel-editor v-model="data" :header-label="headerLabel">
```

```js
headerLabel (label) {
    if (label === 'Phone') return 'Telephone'
}
```

If this does not ok, you may also try to update the label property of [vue-excel-editor].fields variable. Something like this:

``` js
const fields = this.$refs.grid.fields
fields[5].label = 'ABC'
```

**Comment by sleepKele233** [comment]
Can I merge cells
![image](https://github.com/cscan/vue-excel-editor/assets/130077379/8da0eba2-599e-4eda-b736-090bfb84cd10)
like this

**Comment by sleepKele233** [comment]
Can I merge cells

**Comment by sleepKele233** [comment]
Can I merge cells or header
