### ISSUE TITLE
CSV-Export doesn't work

### ISSUE THREAD

**Issue by egwald** [cscan/vue-excel-editor#42]
<button @lcick="exportAsCsv"> Export CSV </button>

exportAsCsv () {
        const format = 'csv'
        const exportSelectedOnly = true
        const filename = 'test'
        this.$refs.grid.exportTable(format, exportSelectedOnly, filename)
    }
CSV-Export doesn't work!

The Excel-Export works fine.

**Comment by cscan** [comment]
May be I apply the compression. I have skipped it when it detects csv format. Please try v83

**Comment by egwald** [comment]
The same bug with v83.

**Comment by cscan** [comment]
There may be some issues in SheetJS lib. Let me do some test and send bug report if I found any problem.

**Comment by cscan** [comment]
I tried once and found no problem. The output csv file can be opened by both Number and MSExcel.

I see you set exportSelectedOnly, if there is no row selected, it will export nothing. I think this is the problem. You may try to set exportSelectedOnly = false
