### ISSUE TITLE
Drag copy function

### ISSUE THREAD

**Issue by johnlandish** [cscan/vue-excel-editor#43]
Anyway i can drag and copy cells

**Comment by cscan** [comment]
No dragging support in this moment, but it support ctrl-c and ctrl-v hotkey
for one cell content

在 2020年10月27日 週二 19:03，johnlandish <notifications@github.com> 寫道：

**Comment by johnlandish** [comment]
Anyway tips on how to do this? maybe i will add it

**Comment by cscan** [comment]
You may intercept the event ondragover in your outer tag to achieve this. You would like to study from the net. e.g. https://www.w3schools.com/html/html5_draganddrop.asp
