### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by johnlandish** [cscan/vue-excel-editor#44]
![Screen Shot 2020-10-27 at 11 24 21](https://user-images.githubusercontent.com/39877398/97295606-6f100e80-1847-11eb-9464-fa571fd896d5.png)

**Comment by johnlandish** [comment]
How to make it dark mode?

**Comment by cscan** [comment]
You could override the css under .systable to achieve this

在 2020年10月27日 週二 19:28，johnlandish <notifications@github.com> 寫道：

**Comment by johnlandish** [comment]
any examples?

**Comment by cscan** [comment]
I have no example for that, but you could drill into the style sheet by Chrome and see the class in each tag. Hope this help.
