### ISSUE TITLE
Problems with the options in map

### ISSUE THREAD

**Issue by egwald** [cscan/vue-excel-editor#45]
I need some help.
With "map" the value for "options" should be changed via a method "fetchPRKOPARENT()"

<vue-excel-column field="PRKO-PARENT" label="PRKO-PARENT" width="120px" type="map" :options="prkoParent_dic"/>

mounted:
    this.fetchPRKOPARENT();

data:
    // prkoParent_dic: {'2': 'Testtest', '1': 'Test'},
    prkoParent_dic: {},

methods:
     fetchPRKOPARENT() {
        const _this = this;
        axios.get(`/project_prkoParent_v2`).then(response => {
            _this.prkoParent_dic = response.data;
            console.log('in fetchPRKOPARENT: ', _this.prkoParent_dic); // {'2': 'Testtest', '1': 'Test'}
        }).catch(response => {
            _this.catch(response);
        }).finally(response => {
            _this.finally(response);
        });
    },
    
the error in console:

in fetchPRKOPARENT:  Object 1: "Test" 2: "Testtest"

app.js:132976 [Vue warn]: Error in render: "TypeError: Cannot read property 'length' of undefined"
found in
---> <VueExcelEditor> at node_modules/vue-excel-editor/src/VueExcelEditor.vue
       <VueProjectTabV2> at resources/js/components/ProjectTabV2.vue
         <Root>

Map works fine, if I put the optionsvalue direct in the line:
<vue-excel-column field="PRKO-PARENT" label="PRKO-PARENT" width="120px" type="map" :options="{'2': 'Testtest', '1': 'Test'}"/>

What should I do?

**Comment by cscan** [comment]
You may try to provide a function in prop, something like this

```html
<vue-excel-column type="select" :options="mylist" ...>
```

```js
methods: {
    mylist () {
         return {1: 'Test', 2: 'Testtest'}
    }
}
```

**Comment by egwald** [comment]
Thanks a lot.

**Comment by cscan** [comment]
I found the root caused of it. As the component remembers the Object pointer and get the value when popdown, but the Object pointer has been renew after you execute ```_this.prkoParent_dic = response.data;```. The length error is unexpected and I fixed in v85. But the pointer-renew problem may require your program to consder the following way to insert the values

```js
if (typeof response.data === 'object') {
    for (var member in _this.prkoParent_dic) delete _this.prkoParent_dic[member];
    Object.keys(response.data).forEach(k => (_this.prkoParent_dic[k] = response.data[k]))
}
```
