### ISSUE TITLE
How to set a default value in "map"

### ISSUE THREAD

**Issue by egwald** [cscan/vue-excel-editor#47]
How to set a default value in "map" and showing it in the table?

Map

The "map" typed column is the same as "select" typed column, but the record value is not the same as the display text. The options prop required to provide the mapping of the value and text.

<vue-excel-column field="gender" label="Gender" type="map" width="50px" :options="{M:'Male','F':'Female'}

**Comment by cscan** [comment]
No default is provided, you may set it in v-model object
