### ISSUE TITLE
Readonly column not reactive

### ISSUE THREAD

**Issue by kentlee87** [cscan/vue-excel-editor#48]
First of all, thanks for the awesome component.

I found out a problem when I changing the readonly props at runtime in vue-excel-column component, it won't take effect.

It only take the value that was initially set during render/mounted. There are no refresh method in the component to refresh the component. I have to do manual reload using v-if.

Hope the author can look into this small bug.

**Comment by cscan** [comment]
You could set the readonly after mounted by the following codes:

```js
this.$refs.grid.fields.map(f => {
    if (f.name === 'myfield') f.readonly = isReadonly
})
```
