### ISSUE TITLE
Import Excel function not working properly

### ISSUE THREAD

**Issue by setamodius** [cscan/vue-excel-editor#49]
I am trying to import a 2 column excel file but the file is not being imported. If I try to import a three column file, I don't have any problems.
When I examined the VueExcelEditor.vue file, I saw the relevant code on line 1721.

`importData = importData.filter (rec => Object.keys (rec) .length> 2) .map ((rec) => {`

Is it any problem to have length> = 2 instead of length> 2?

**Comment by cscan** [comment]
This is a bug. Fixed in v1.3.89. Thanks for your report.
