### ISSUE TITLE
Can't the component height be fixed?

### ISSUE THREAD

**Issue by taylous** [cscan/vue-excel-editor#5]
- environment
vue: 3.1.3
@vue/cli: 4.3.1

- description
Is it possible to statically give the height of a component without a header list and records (data)?
I tried giving style to the component and css effect on the table itself, but to no avail.

i would appreciate your reply.

**Comment by cscan** [comment]
You may set the height attribute. But I found that it affects the calculation of the paging. Will fix it

**Comment by cscan** [comment]
The paging calculation is fixed. Please get the latest.

**Comment by taylous** [comment]
Thank you for answer!
