### ISSUE TITLE
How "selectedRows" find

### ISSUE THREAD

**Issue by egwald** [cscan/vue-excel-editor#51]
How this works?
Do something when user select/unselect the rows
The selected or unselected rows will be passed to the provided trigger method

<template>
    <vue-excel-editor v-model="jsondata" @select="onSelect">
    ...
    </vue-excel-editor>
</template>

methods: {
    onSelect (selectedRows) {
      console.log(selectedRows)
    }
}

I need a method to reload the content of a second table after selection a row of the first table.

**Comment by cscan** [comment]
When user click on the "number" rows, it will trigger the @select event which passed 2 arguments to it. The first one is the selectedRow position and the 2nd one is select/unselect boolean. You could obtain the exact row content by $refs.mygrid.getSelectedRecords(). You may do a try. Thanks.

**Comment by egwald** [comment]
Thanks, I found it at this moment too.
