### ISSUE TITLE
Can I export the excel file in a customized?

### ISSUE THREAD

**Issue by Alertis** [cscan/vue-excel-editor#53]
Hi, can I export the excel file in a customized way? For example, bold font, colored cell etc.

**Comment by cscan** [comment]
This component only exports simple Excel. For formatting, you may try other
library such as xlsx-template or ExcelJS and directly put your json data
into it.

在 2020年12月4日 週五 19:14，Osman Yavuz Demir <notifications@github.com> 寫道：

**Comment by Alertis** [comment]
Thanks you
