### ISSUE TITLE
async autocomplete

### ISSUE THREAD

**Issue by isbincApps** [cscan/vue-excel-editor#55]
Hi, first of all the library is really great.

is there a way to fill the autocomplete by calling a db in the server

**Comment by cscan** [comment]
type='select' should address your needs. Its prop "options" supports the async function, or your function return a promise, something like this:
```html
<vue-excel-column field="x" label="Test" type="select" :options="getXOptions" />
```
```js
methods: {
   async getXOptions () {
      const result = await getXFromServer()
      return result
   }
}
```

**Comment by isbincApps** [comment]
thanks @cscan, but If I want to type something and make async filter, what I have to do?

**Comment by cscan** [comment]
type="select" supports typing. The dropdown list depends on your async function. Component will pass the edit value and record to the function, you may try this:

```js
methods: {
   async getXOptions (val, rec) {
      if (val === '') return []
      const result = await getXFromServer(val) // val contains what you typed
      return result
   }
}
```

**Comment by isbincApps** [comment]
awesome, thank you very much

**Comment by isbincApps** [comment]
it works, but why is so slow setting the value in the grid

**Comment by isbincApps** [comment]
is there any possibility to set a debounce function in async getXOptions (val, rec)

**Comment by cscan** [comment]
Slow because of the await. You may add some caching to speed the things up.

**Comment by isbincApps** [comment]
I'm trying to do something like like this, but i'm getting 
   
   list.slice is not a function
   `
   async getXOptions () {
       if (val === '') return []
      return debounce(async () => await getXFromServer(), 500) 
   }
   `
