### ISSUE TITLE
Autocomplete improvements

### ISSUE THREAD

**Issue by atrX** [cscan/vue-excel-editor#57]
I've been working with this library for a few weeks now for a client project and during our last demo we got some feedback regarding the excel editor's autocomplete functionality:

- It would be useful to be able to show more than 10 items for select/map inputs. A user often doesn't know all the possible values for a given select input and might not find the correct one if it's not presented to them directly.
- It would be more user-friendly if you could open the dropdown by clicking anywhere in the cell, not just on the little chevron/triangle icon.

My team and I are willing to put in the development time to make a pull request for this, we just want to make sure it wouldn't be rejected. If either of these changes are something you'd prefer not to have on the main repo we can always fork it, though we'd obviously prefer to not have to keep a fork up-to-date.

**Comment by cscan** [comment]
For the 10 items, I also want to add the scrolling support in the autocomplete popup. I really apprecaite it if you want to make PR for this.

For the dropdown clicking effect, I can make it by adjusting some numbers. Will push it in next version.

**Comment by atrX** [comment]
> For the 10 items, I also want to add the scrolling support in the autocomplete popup. I really apprecaite it if you want to make PR for this.

Good to hear. Looking at our current sprint goals I think I might be able to fit it in somewhere, if not we'll put it on the planning for the next one. 🙂

**Comment by mvhaen** [comment]
Great news!

**Comment by cscan** [comment]
Hello guys, please try v1.3.91. This supports scrolling and you could set the max length of the autocomplete list by the prop "autocomplete-count"

**Comment by atrX** [comment]
> Hello guys, please try v1.3.91. This supports scrolling and you could set the max length of the autocomplete list by the prop "autocomplete-count"

Works like a charm! Thanks for saving us some development time. 🙂 
Did you get a chance to look at the other issue I mentioned?

**Comment by cscan** [comment]
For select/map typed column, you may press "space" to show the list. Since user may want to click on the cell for editing purpose, I choose to keep this feature. May be I make an option for disable the editing feature. Will visit this later.
