### ISSUE TITLE
Import & Validators

### ISSUE THREAD

**Issue by bacontech** [cscan/vue-excel-editor#58]
Currently, if a user imports a csv/excel, and a cell fails a custom validation, then nothing happens (from the users perspective).  An error is logged to the console.

It would be preferable to allow the import, and display the errors on the cells (similar experience as if a user typed the errors manually).

If the above suggestion is not accepted, then I'd love to have a callback or similar so I can notify the user of an error during importing.

Thanks you for your work!

**Comment by cscan** [comment]
Good idea, will implement a callback for handling error

**Comment by cscan** [comment]
Please try v1.3.91, you could pass the errorCallback by 2nd argument i.e. importTable(cb, errCb)
