### ISSUE TITLE
Can I save the uploaded file as it is?

### ISSUE THREAD

**Issue by taylous** [cscan/vue-excel-editor#6]
- environment
vue: 3.1.3
@vue/cli: 4.3.1

- description
After uploading the excel file, I want to change the data and save it back to the original file. Is there any way? (Now I am using it as exporting again, but I am worried because there are too many files.)

i would appreciate your reply.

**Comment by cscan** [comment]
You may write custom import/export interface by yourself. For import, you could use some Excel JS library to extract the file you like, extract he values and update the v-model array. For export, some Excel JS library can also do for you.
