### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by sailfish009** [cscan/vue-excel-editor#60]
about 500 columns, need some scrollbar.

**Comment by cscan** [comment]
The H scroll bar is hidden in the status bar

**Comment by sailfish009** [comment]
@cscan How to use H scroll bar explicitly/normal ?

**Comment by cscan** [comment]
It shows normal in my grid. May be too many columns in your grid, the scroll button is too small to see

**Comment by sailfish009** [comment]
@cscan never mind, transposed 2d array, now V scroll bar shows fine.

**Comment by sailfish009** [comment]
> 
> 
> It shows normal in my grid. May be too many columns in your grid, the scroll button is too small to see

@cscan 

In such a case, in order to set the width of the scrollbar and adjust the scroll ratio, which part of the component source should I look at?
