### ISSUE TITLE
cell color

### ISSUE THREAD

**Issue by sailfish009** [cscan/vue-excel-editor#62]
Can I specify the color of the cell? If you can specify, how many bits of color are supported?

**Comment by cscan** [comment]
You may try cell-style prop to pass a function which return the additional style of the cell. Something like this:

```html
<vue-excel-editor cell-style='mystyle' ...>
```

```js
mystyle (record, column) {
   if (column === 'status' && record.finish < '15%' ) return {'background-color': 'red'}
   else {'background-color': 'white'}
}
```
