### ISSUE TITLE
vue-excel-editor width

### ISSUE THREAD

**Issue by sailfish009** [cscan/vue-excel-editor#63]
I would like to set it the same as the width of the upper button on the screen. It doesn't matter if there are enough columns, but if the number of columns is small, it looks unnatural like the screen. Is there a way to automatically set the width? I tried applying the settings as follows, but it does not work. 

**vue-excel-editor v-models="rows" filter-row width='200%'**

**Comment by sailfish009** [comment]
[width is narrow, so text broken]
![image](https://user-images.githubusercontent.com/17582766/105939608-e6e71280-609c-11eb-8a7d-5825f30f264a.png)

[adjust width by hand, now text fine]
![image](https://user-images.githubusercontent.com/17582766/105939785-31688f00-609d-11eb-867e-a3227aa2c6ed.png)

**Comment by cscan** [comment]
I remember you could customize the text in status bar by passing your function in localizedLabel prop. Please refer to readme. Thanks.

**Comment by sailfish009** [comment]
@cscan  nevermind fortunately, i transposed 2d array again.
