### ISSUE TITLE
select/unselect

### ISSUE THREAD

**Issue by egwald** [cscan/vue-excel-editor#64]
My code:
`onSelect(selectedRows) {

        console.log(selectedRows)

        if (this.$refs.grid.selectedCount === 1) {

            console.log('this.$refs.grid.selectedCount === 1', this.$refs.grid.selectedCount === 1)

            this.disabled=false

            } else

            return this.disabled=true

    },`
            
 Select works like expected, but unselect gives  `this.$refs.grid.selectedCount === 1` every time true.
How watch the select/unselect of the same row?

**Comment by cscan** [comment]
A super way to understand the callback is printing all the arguments by:

```js
mycallback(...arg) {
   console.log(arg)
}
```

Anyway, the 2nd argument will show the select/unselect direction. Thanks.

**Comment by egwald** [comment]
Thanks a lot!
