### ISSUE TITLE
Specify the number of rows per page 

### ISSUE THREAD

**Issue by sailfish009** [cscan/vue-excel-editor#66]
For some reason, I only want to see 5 rows per page. Can it be set? 

Thanks.

**Comment by cscan** [comment]
Please study the page prop from readme document.

**Comment by sailfish009** [comment]
Thanks!
`this.$refs.grid.pageSize = 5`

**Comment by sailfish009** [comment]
@cscan 

I set the number of rows per page to 5 and actually tested it, and there seems to be a bug. As shown in the figure below, the number of random rows is displayed on one page regardless of the setting value. In the figure, there are 17 input rows. The desired action is to create 3 pages of 5 each, and the last page creates a page with 2 rows, so it seems that all 4 pages should be created. 

`<vue-excel-editor ref="grid" v-show="finished" v-model="rows" autocomplete filter-row />`

`this.$refs.grid.pageSize = 5 // set this prop at mounted `

![image](https://user-images.githubusercontent.com/17582766/107164469-7fad5480-69f2-11eb-9a7b-079a96cd3b0d.png)
