### ISSUE TITLE
Horizontal scroll programmatically?

### ISSUE THREAD

**Issue by sailfish009** [cscan/vue-excel-editor#67]
I am using the moveTo() function well. However, there is one problem. In the case of the cell on the right, the selected cell is completely visible, but in the case of the cell on the left, only a small portion of the selected cell is visible, so you must manually scroll horizontally to see which cell is selected. Is there a way to automatically bring the selected cell to the center of the screen when calling the moveTo() function?

**Comment by cscan** [comment]
I remember the moveTo will ensure the visibility of the cell by scrolling horizontally and vertically, but not centre. You may study the codes in moveInputSquare for your design. It involes some calculation behinds:

```js
      // Adjust the scrolling to display the whole focusing cell
      if (!this.currentField.sticky) {
        const boundRect = this.$el.getBoundingClientRect()
        if (cellRect.right >= boundRect.right - 12)
          this.tableContent.scrollBy(cellRect.right - boundRect.right + 13, 0)
        if (cellRect.left <= boundRect.left + this.leftMost)
          this.tableContent.scrollBy(cellRect.left - boundRect.left - this.leftMost - 1, 0)
      }
```

You may reset the position in @cellFocus event.
