### ISSUE TITLE
Import/Export Table with ReadOnly Columns

### ISSUE THREAD

**Issue by hannesroth88** [cscan/vue-excel-editor#68]
First of all great libary 💯 
I have a ReadOnlyColumn and I also want to use the Import/Export Table Function.
Is there any way to use it together? 
Have the Export Table Function use Protected Cells on the ReadOnly Columns in the output Excel File?
Also Importing with ReadOnly Columns is not working right?

**Comment by cscan** [comment]
You could unset the readonly before the import by:

```js
   this.$refs.editor.fields.forEach(field => field.readonly = false)
``` 

and set back it in callback function after the import

**Comment by hannesro** [comment]
I tried so. The issue is when just closing the import dialog. Then the readOnly cells will be editable. 
I would also be fine to get an callback after closing.

**Comment by cscan** [comment]
You may need to call import explicity, u could specify the callback in
argument

在 2021年2月8日 週一 14:22，Hannes Roth <notifications@github.com> 寫道：

**Comment by hannesro** [comment]
i dont understand.

this is how i do it:

```

export default {
  methods: {
    exportAsExcel() {
      const format = "xlsx";
      const exportSelectedOnly = false;
      const filename = "FileName";
      this.$refs.grid.exportTable(format, exportSelectedOnly, filename);
    },
    importExcel() {
      //remove readOnly while importing
      // TODO Bug, if abort, Columns are not read only anymore
      this.activateReadOnly(false)
      this.$refs.grid.importTable(
        (success) => {
          // will run after successfully import
          console.log("importSuccessCb:" + JSON.stringify(success)); 
          this.activateReadOnly(true)
        },
        (error) => {
          // will run after error import
          console.log("importErrorCb:" + JSON.stringify(error));
          this.activateReadOnly(true)
        }
      );
    },
    activateReadOnly(readOnly){
      this.$refs.grid.fields.map((f) => {
        if (
          f.name === "material" ||
          f.name === "vendorNr" ||
          f.name === "vendorName" ||
          f.name === "shortText" ||
          f.name === "scheduledQuantity"
        )
          f.readonly = readOnly;
      });
    },

 
};
```


If import dialog is aborted readonly Columns are editable.

**Comment by cscan** [comment]
How about you call $forceUpdate after you set/unset the readonly flag?

```js
activateReadOnly(readOnly){
   this.$refs.grid.fields.map((f) => {
      if (
         f.name === "material" ||
         f.name === "vendorNr" ||
         f.name === "vendorName" ||
         f.name === "shortText" ||
         f.name === "scheduledQuantity"
      )
         f.readonly = readOnly;
   });
   this.$refs.grid.$forceUpdate()
},
```

**Comment by hannesro** [comment]
Thanks for your help. Unfortunately it didn't solve my issue.
1. if I set readonly=false before import action and dialogbox is closed, it's not set back to readonly=true.
2. If i set to readonly=true before import, i get
> Readonly column detected: vendorNr"  

Could you also throw an error if dialog box is closed?

**Comment by cscan** [comment]
Could you help to provide more information about "It's not set back to readonly=true". Did your callback call after successfully import? Can you see "importSuccessCb:" text? Did your activateReadOnly method be called after successfully import? Can you also print the readonly value in setTimeout routine after set/unset? Actually you could debug yourself by looking at the method doImport ( ) in VueExcelEdutor.vue. Hope this help.

**Comment by hannesro** [comment]
By set to readonly I mean user cannot type in those cells. 

It all works perfektly when 1) import was successfully, even importSuccessCb is logged. After the success callback i set my 5 columns back to readonly. 
2) import ended with error also works and I set the 5 columns back to read only. So far so good. 

The problem is with 3) I think I couldn't explain to good. 
What I mean is user wants to import some excel file, 
a) user presses button, 
b) program sets the 5 columns to not readonly (for import to work) 
c) program calls your importTable() function, dialog box opens to choose file. And User cancels the dialog, without choosing any file. 
Now my program doesn't get any callback and my 5 columns are still editable which I don't want.

**Comment by cscan** [comment]
Ok. I think part of the problem has solved. The remain problem is only how to restore the readonly status after dialog cancelled. It is very hard to achieve by redirect the doImport event to your custom function. Anyway, raising an error event if user click cancel is a good way to solve your problem. Will do it in later version. Thanks.
