### ISSUE TITLE
Page Event?

### ISSUE THREAD

**Issue by sailfish009** [cscan/vue-excel-editor#69]
Can I get an event when I click the page control (First / Previous / Next / Last) ? 

At that point, I have to change the value of the external element. 

Thanks.

**Comment by cscan** [comment]
Will consider it in future version

在 2021年2月8日 週一 12:03，sailfish009 <notifications@github.com> 寫道：

**Comment by sailfish009** [comment]
@cscan thanks, at this moment, will implement custom button instead of page control.

until then, it would be great if i can set default page control prop hide/invisible.

**Comment by cscan** [comment]
Yes, you can set no-paging prop to disable the paging feature

**Comment by egwald** [comment]
It is possible to use the **$refs.grid.pageBottom** to check the page control (First / Previous / Next / Last) ?

**Comment by cscan** [comment]
Yes, of course many ways to do that. But I think salifish wants a pageChange event and obtain which records are showing

**Comment by egwald** [comment]
Can you show me, how **watch** the pageBottom?

**Comment by vitiok78** [comment]
> Can you show me, how **watch** the pageBottom?

You can watch **pageTop** variable:

```html
 <vue-excel-editor ref="excel">
```

```javascript
mounted() {      
  this.$watch("$refs.excel.pageTop", () => {
          this.doSomething();
  });
}
````

**Comment by egwald** [comment]
oh, thanks a lot!

**Comment by cscan** [comment]
Yes, watch the pageTop is a tricky way to do the same

**Comment by cscan** [comment]
page-changed event is added in version v1.3.94
