### ISSUE TITLE
CDN or UNPKG

### ISSUE THREAD

**Issue by amchconsult** [cscan/vue-excel-editor#71]
Hi,
I am trying CDN or UNPKG but it is not working. Could you please take a look?
I need the UMD or JS for use as global CDN.
Thank you

**Comment by cscan** [comment]
I tried before, but I don't know how to do that in a right way

**Comment by amchconsult** [comment]
Let me see if I can find a way to do it or fix.

**Comment by yuan8** [comment]
https://eslint.vuejs.org/rules/no-v-for-template-key-on-child.html

**Comment by cscan** [comment]
I found a CDN, you may try this:
https://www.jsdelivr.com/package/npm/vue-excel-editor
