### ISSUE TITLE
How to use cell-click?

### ISSUE THREAD

**Issue by hsuanmax** [cscan/vue-excel-editor#74]
I use cell-click event, but it is not work.

<vue-excel-editor v-model="dataList" v-if="dataList.length" @cell-click="test">
..........
</vue-excel-editor>

**Comment by vitiok78** [comment]
Try @cellClick

**Comment by hsuanmax** [comment]
It is work, thanks

**Comment by cscan** [comment]
Hi, the event will be changed to cell-click in version v1.3.94. Appreciate your attention.
