### ISSUE TITLE
How to dynamic display column?

### ISSUE THREAD

**Issue by hsuanmax** [cscan/vue-excel-editor#76]
When I set invisible in column, it is work, but when i call api then change invisible attribute, it is not work
How to do it?

**Comment by cscan** [comment]
I did not provide any api to change the invisible state. You may change the invisible state in fields variable and call $forceUpdate after that. Something like this:

```js
const field = this.$refs.grid.fields.find(f => f.name === 'birthday')
field.invisible = false
this.$refs.grid.$forceUpdate()
```
