### ISSUE TITLE
Conditional styling on one cell based on value of another cell

### ISSUE THREAD

**Issue by HowdyChad** [cscan/vue-excel-editor#77]
Hey, this component is really great. Thank you!

So far, I've been able to do everything I need. However, I'm unsure how to accomplish some dynamic styling.

Let's say we have 2 columns. Column A has a numeric value and a name of "colA" and Column B is readonly and has a name of "colB". Column B is using the readonlyStyle.

If column A is less than .25 then I want to style Column B a shade of red, otherwise it should have the default readonlyStyle.

I was thinking of hooking into :change and checking the value of the newVal argument.

How would I go about styling "colB" based off the value of "colA", overwriting the readonly style if < .25, but reverting back to the readonlyStyle if >= .25?

**Comment by cscan** [comment]
It could be achieved by the cellStyle prop, e.g.:

```html
<vue-excel-editor cell-style="myMethod" ....>
```

```js
myMethod (rec, col) {
   if (col.name === 'birth') return {'color': 'red'}
   if (col.name === 'phone' && rec.gender === 'F' ) return {'color': 'blue'}
   return {'color': 'white'}
}
```
