### ISSUE TITLE
Exclude columns from export?

### ISSUE THREAD

**Issue by HowdyChad** [cscan/vue-excel-editor#78]
Is there a way to exclude columns when exporting? If I have v-if on vue-excel-column and it starts as false and never becomes true, the the columns are not exported just like I would expect. However, if v-if ever is true (either at initial load, or later) ... but then false, the columns do not dissappear (even after a forceUpdate), and they are present in my exported file.  I've tried with the invisible and with v-show, but never got the results I was after.

I even tried to remove the properties on my object itself, and re-add them back, but the headers still were visible.

What would be the best way to exclude certain columns from exporting ... even if that means hiding them right before exporting and making them visible again right after exporting?

Thanks again for a fantastic component. It has tons of really useful functionality!

**Comment by cscan** [comment]
Hi, the first thing I would like to emphase, the component only looks at the vue-excel-column during "mounted", and never see it after displayed. If you change anything on vue-excel-column, there is no response. If you want to dynamically change the invisible state of any col, I suggest you take a look on the variable this.$refs.yourreferenceid.fields and change the invisible attribute of the appropriate item. Something like this:

```js
this.$refs.yourreferenceid.fields.forEach( field => {
   if (field.name === 'phone') field.invisible = false
})
```

If you want more flexiblity when exporting, I suggest you also take a look on the below source:

```js
    exportTable (format, selectedOnly, filename) {
      this.processing = true
      setTimeout(() => {
        const wb = XLSX.utils.book_new()
        let ws1 = null
        let data = this.table
        if (selectedOnly)
          data = this.table.filter((rec, i) => this.selected[i])
        const mapped = data.map(rec => {
          const conv = {}
          this.fields.forEach(field => conv[field.name] = rec[field.name])
          return conv
        })
        ws1 = XLSX.utils.json_to_sheet(mapped, {
          header: this.fields.map(field => field.name)
        })
        const labels = Array.from(this.labelTr.children).slice(1).map(t => t.children[0].innerText)
        XLSX.utils.sheet_add_aoa(ws1, [labels], {origin: 0})
        ws1['!cols'] = Array.from(this.labelTr.children).slice(1).map((t) => {
          return {
            width: t.getBoundingClientRect().width / 6.5
          }
        })
        XLSX.utils.book_append_sheet(wb, ws1, 'Sheet1')
        filename = filename || 'export'
        switch (format) {
          case 'csv':
            if (!filename.endsWith('.csv')) filename = filename + '.csv'
            break
          case 'xls':
            if (!filename.endsWith('.xls')) filename = filename + '.xls'
            break
          case 'xlsx':
          case 'excel':
          default:
            if (!filename.endsWith('.xlsx')) filename = filename + '.xlsx'
            break
        }
        if (filename.endsWith('.xlsx'))
          XLSX.writeFile(wb, filename, {
            compression: 'DEFLATE',
            compressionOptions: {
              level: 6
            }
          })
        else
          XLSX.writeFile(wb, filename)

        this.processing = false
      }, 500)
    }
```

You could see that my export routine is quite straight forward. I use the popular xlsx component. I export all the "th" in labelTr.children. Note that labelTr is the "colgroup" in "table". For the "colgroup" html, it is:

```html
          <colgroup>
            <col style="width:40px">
            <col v-for="(item, p) in fields" v-show="!item.invisible" :key="p" :style="{width: item.width}">
            <col v-if="vScroller.buttonHeight < vScroller.height" style="width:12px">
          </colgroup>
```

The showing of the col depends on the attr invisible, that's all of the magics.

I suggest you create your custom export routine and make any changes you desired. Thanks a lot.
