### ISSUE TITLE
Transpose data

### ISSUE THREAD

**Issue by andref94** [cscan/vue-excel-editor#79]
Is there a way to transpose data? For example, given this object: 
`
let mydata = [
   { prop1: "a", prop2: "b" },
   { prop1: "c", prop2: "d" }
]
`
I want to show in colum A values "prop1", "prop2", in colum B values "a", "b" and in column C values "c", "d"

**Comment by cscan** [comment]
The current component only accepts horizontal approach. Is there any way to transform it in Vue level?  I have a case that showing the ini setting by converting the horizontal format to vertical.
