### ISSUE TITLE
UI bug after excel import and filter

### ISSUE THREAD

**Issue by joelbudu** [cscan/vue-excel-editor#8]
Starting with some exisiting data as below:

<img width="690" alt="Screenshot 2020-06-02 at 20 40 28" src="https://user-images.githubusercontent.com/888508/83624654-ca84eb80-a58a-11ea-8e6c-71743f90192a.png">

When an import is done via excel and some rows are filtered out by modifying the data object results in this:

<img width="733" alt="Screenshot 2020-06-02 at 20 41 14" src="https://user-images.githubusercontent.com/888508/83624652-c953be80-a58a-11ea-9c81-0e90a7986895.png">

This seems to break after version 1.3.48

**Comment by cscan** [comment]
Sorry, I could not simulate your problem. My import test is successful without problem.

![Screen Shot 2020-06-03 at 9 10 26 PM](https://user-images.githubusercontent.com/3221271/83640465-bcf95100-a5de-11ea-80ef-d39c1c3a9175.png)

How many record in your imported Excel?
What is your expected output?
Did you set any filter before import?
Did you set the keyFields for some columns?

**Comment by joelbudu** [comment]
So I'm filtering the attached v-model right in the import callback. so I'm effectively deleting some rows right after import

**Comment by cscan** [comment]
Good to hear that you have alternative way to solve this

**Comment by joelbudu** [comment]
No I didn't mean I have an alternative way to solve this. I was explaining how it happens...

**Comment by cscan** [comment]
Could you show me your codes and email me your Excel file?

**Comment by cscan** [comment]
Or you call this.$forceUpdate() after delete rows?

**Comment by joelbudu** [comment]
let me try the this.$forceUpdate() if it doesn't work then i'll share codes.

**Comment by joelbudu** [comment]
Had to do it this way  this.$refs.excelComponent.moveTo(this.execlData.length - 1)

**Comment by cscan** [comment]
Yes, since the newRecord has a setTimeout call which move the cursor to the last inserted record.
