### ISSUE TITLE
Optional map field

### ISSUE THREAD

**Issue by IlkoMichler** [cscan/vue-excel-editor#80]
Hello!

In my datasets I have a filed, that carries mostly values from a predefined value-name map. Sometimes there is but a value, that is valid not being listed in the map. So I am fighting with sometimes give a selection/map and sometimes just accept a plain value in a single column. I but have troubles to manage to have it this way. My try was:

`          <div v-if="checkItem(this.$refs)">`
`            <vue-excel-column field="MARA_MATKL" label="[MARA-MATKL] Warengruppe"`
`                              type="map" :options="myBGR002_dict" width="120px"/>`
`          </div>`
`          <div v-else>`
`            <vue-excel-column field="MARA_MATKL" label="[MARA-MATKL] Warengruppe" width="120px"/>`
`          </div>`
``

It does not work this way, since the options binding is ether valid or not for a complete column.

Any hint to a solution for this? How should I do this?
Thanks for any advice!

Cheers and happy Easter to everybody!

**Comment by cscan** [comment]
The map field supports calculated field or async method result. You may try to place condition in calculated field, something like this:

```html
<vue-excel-column field="MARA_MATKL" label="..." type="map" :options="optionsDict" width="120px"/>
```

```js
optionsDict () {
   if (this.checkItem(this.$refs))
      return this.myBGR002_dict
   else
      return {}
}
```

**Comment by IlkoMichler** [comment]
I have to continue on my question, because it got more difficult:

In the suggested function "this.checkItem(this.$refs)" i have to decide upon the value of another cell in the same row what the select or map should deliver. I have troubles to address the neighboring cell to check the value.

Could you please give me a hint how to access it?
At what time is the select or map set up? Is it at mount or when clicking the selection symbol (down arrow) in the cell??

Thanks!
I wish you the best!

Cheers Ilko
