### ISSUE TITLE
how to customize record-label

### ISSUE THREAD

**Issue by kinhoon** [cscan/vue-excel-editor#82]
I tried to customize the record label by doing the following:

1. adding `record-label` prop
`<vue-excel-editor record-label="getRowLabel">`

2. adding the function `getRowLabel(pos, row)` to `methods`

However, loading the page gives me the following error in console.
`vue.runtime.esm.js:1888 TypeError: e.recordLabel is not a function`

What is the correct way of customizing record-label?

**Comment by cscan** [comment]
You may miss the semi-colon:

```html
<vue-excel-editor :record-label="getRowLabel">
```
