### ISSUE TITLE
select type error

### ISSUE THREAD

**Issue by kinhoon** [cscan/vue-excel-editor#83]
I tried to create a grid with several select columns

`<vue-excel-editor v-model="xx" remember autocomplete no-footer no-paging no-header-edit disable-panel-setting>`
`  <vue-excel-column field="A" label='["true", "false"]' type="select" :options='["true", "false"]' />`
`  <vue-excel-column field="B" label="['boolean','int16','int32']" type="select" :options="['boolean','int16','int32']" />`
`  <vue-excel-column field="C" label="[0,1,3,4]" type="select" :options="[0,1,3,4]" />`
`</vue-excel-editor>`

Note that I tried different type of array:
- array of string as described in the documentation, `["true", "false"]`
- array of single quoted string, `['boolean','int16','int32']`
- array of number, `[0,1,3,4]`

The field name is purposely made the same as the options content.

![image](https://user-images.githubusercontent.com/46112444/116353775-f0ae1c80-a829-11eb-91d8-4f8b86475611.png)

All these three columns exhibit the same error when I
- clicked on the dropdown arrow (expecting drop down with list of value), and
- tried to key in value (expecting autocomplete drop down with list of value).

![image](https://user-images.githubusercontent.com/46112444/116353903-29e68c80-a82a-11eb-92bd-60c160ca1276.png)

I tried to add a sorting function to all of these three columns but same result. In both cases, the drop down was not shown.

`<vue-excel-column field="C" label="[0,1,3,4]" type="select" :options="[0,1,3,4]" :sort="onSort" />`
`onSort (a,b) { return a.toString() > b.toString() }`

What could be the possible issue?

**Comment by cscan** [comment]
I have no problem, my syntax is:

```html
      <vue-excel-column field="role" label="Role" type="select" width="70px" :options="['guest','user','master','reader','admin','disable']" />
```

Show me the following out:
```js
this.$refs.grid.fields.forEach(f => console.log(f.options))
```
This is the codes that show the error, line 2569, 2570, I believe the field.options is not an array
![image](https://user-images.githubusercontent.com/3221271/116780493-c40b3680-aaaf-11eb-9b38-99f7d59df3ce.png)

**Comment by kinhoon** [comment]
The `options` is passed as follows:
![image](https://user-images.githubusercontent.com/46112444/116780976-77752a80-aab2-11eb-80b4-83f225d06b3c.png)

Where `csvSchema.columns` is as follows:
`[
{ "field": "disable", "type": "select", "width": "40px", "options": "['true', 'false']", "invisible": false, "keyField": false },
{ "field": "name", "type": "string", "width": "100px", "options": null },
{ ... }
]`

One difference is instead of putting the array value directly into `<vue-excel-column>`, the array is passed to `options` as an object member. In this case, what is the proper way of passing it?

Thanks.

**Comment by cscan** [comment]
The options prop accepts a function or computed variable

BTW, I don't suggest to use "v-for" for vue-excel-column tag

**Comment by kinhoon** [comment]
The columns are configured by user, therefore `v-for` is used to iterate the setting and setup `vue-excel-column`.
What is other better way to handle this if not using `v-for`?

**Comment by cscan** [comment]
You could change the fields variable any time after mounted, and called forceUpdate() after changed. Actually the vue-excel-column is just a nice tag for building the fields variable when mounted.

**Comment by kinhoon** [comment]
Great !!! Thanks !!!
