### ISSUE TITLE
Reinitialize column header

### ISSUE THREAD

**Issue by kinhoon** [cscan/vue-excel-editor#86]
I found that in `VueExcelEditor`, there are `reset` and `resetColumn` functions. I tried to use it to remove all `vue-excel-coumn` added, and add another different set of columns. These methods sometimes work sometimes not.

`this.$refs.csvEditor.reset();`
`this.$refs.csvEditor.resetColumn();`
`this.$refs.csvEditor.$forceUpdate();`

I  understand that `VueExcelEditor` reads columns info at startup, but is there a simple workaround to force it to read and reload the column again, by resetting the state back to its virgin state?

The purpose is to allow using `v-for` in `vue-excel-column`.

`<vue-excel-editor v-model="csvModelSorted" ref="csvEditor" no-header-edit disable-panel-setting>`
`	<vue-excel-column v-for="(item, idx) in columns" :key="'' + idx + item.$state"`
`					  :field="item.field" :label="item.label" type="item.type" :width="item.width" />`
`</vue-excel-editor>`

**Comment by cscan** [comment]
I am doing this by changing the variable "fields" and call $forceUpdate after that. Changing the vue-excel-column will not take effect since right now I just look at it during initialization.  In readme, there is an example:
https://github.com/cscan/vue-excel-editor#change-the-column-label

**Comment by cscan** [comment]
Actually I want to do your desired way to reflect the changes of the vue-excel-column slots by the resetColumn function, however it does not work as expected. Or you may try to call $forceUpdate in a setTimeout routine. Please let me know the result.

**Comment by kinhoon** [comment]
Changing of field `label` by matching field `name` may not work in my scenario, as different sets of column has totally different name-label pairs. However, is it possible to iterate through `fields` and modify its `name`? i.e., modifying it from `['a1', 'a2', 'a3']` to `['b1', 'b2', 'b3', 'b4', 'b5']`.

I'll try the `setTimeout` trick suggested later tonight.

Another thing is, in `VueExcelEditor.vue`, I found it `watch` for `fields` but only `store` and `$emit` `setting`. In `computed`, `setting` `setter` skips if new fields length is different from existing fields length. Do these 2 affect the handling of `vue-excel-column` changes?

**Comment by cscan** [comment]
It is not a difficult steps to loop the array to match the name and update the fields variable.
