### ISSUE TITLE
Fix: Use nFilterCount at panelFilter/v-if

### ISSUE THREAD

**Issue by ste-gr** [cscan/vue-excel-editor#87]
Hi,
I found some problem here:

https://github.com/cscan/vue-excel-editor/blob/158f0ed69cdeeefba9f163a273109581aeb30cc3/src/panelFilter.vue#L69

Think it should be "filteredSortedUniqueValueList.length>**nFilterCount**"

Greetings
Stefan

**Comment by cscan** [comment]
Great. I got it. Thanks.
