### ISSUE TITLE
CSS-Suggestion: Input-Box in PanelFind

### ISSUE THREAD

**Issue by ste-gr** [cscan/vue-excel-editor#89]
https://github.com/cscan/vue-excel-editor/blob/088d7ff5cfdca8b0d40394f53f3b6db6e0381ebe/src/panelFind.vue#L111

There is a lot of space between caret and frame in input-field:
![grafik](https://user-images.githubusercontent.com/84541644/119990068-31838780-bfc8-11eb-87ca-48c2262b3d89.png)

So I would suggest to change the CSS to `width: 100%;`

**Comment by cscan** [comment]
Yes, you are right. Will correct it in next version
