### ISSUE TITLE
Checkboxes in Filters

### ISSUE THREAD

**Issue by getraid** [cscan/vue-excel-editor#9]
Hey, first of all:
Thank you for this awesome component! It really made my work (and the product) way easier!  

But I was wondering about the filtering feature.   
When you right click on a col, you get a modal with the different options to filter through.
There are these checkboxes that are implying that you can select multiple at once.   
But you can't.
Im my case it just uses the one option you wanted to select and starts filtering with that, instead of letting me select multiple at once.
Is that a feature you plan to include at a later point or a bug that was overlooked?

Ah and another thing, that I found weird:   
When something is filtered with regex, sorting on any col seems to sort wrong. 

For example:  "~word1|word2" & ascending sort -> the rows get filtered, but not sorted correctly.

Maybe sorting was done before filtering?
I might, if I have time later, look into the code myself and make a fork. 
But since you know your code better (hopefully), you maybe already know whats the issue :^)

Greetings!

**Comment by cscan** [comment]
Sorry, currently the component does not provide multi-options checkbox list. It involves some complex UI coding.

For the filter+sort problem, I cannot simulate the issue that you meet. Could you show me several screenshots for your issue? Actually the sorting is process in your provided array, but the filter will not change the sorting seq so no matter it is after or before, it does not affect the sorting result.

**Comment by getraid** [comment]
Hey, sorry for responding so late:
I made a screenshot of the issue, but since I'm already working with sensitive data, i blurred the sensitive stuff out. ![img](https://getra.id/cRW.png)
As you can see by the sorting arrow in the field named "Status", that it should be sorting in ascending order. But the entries are mixed through. 
It maybe could be related to the random lowercase/uppercase entries. 
(I work with unformatted excel data, that we somehow ported to a mysql db🤮).

That with the checkbox is a bummer, but thanks for letting me know!

**Comment by cscan** [comment]
Thanks for your screenshot. Could you answer me below questions?
1. Which action you do first? Sort or Filter?
2. Is it resolve by sort again after you see the sorting problem?
3. Can you show me some of the raw data (column status) and the grid html tags?

I guess you may have some hidden control char in content .e.g LF

**Comment by getraid** [comment]
1. Doesn't matter, same outcome.
2. No, same outcome
3. 
```
 <vue-excel-editor
    ref="exedit"
    v-model="jsondata"
    autocomplete
    select
    filter-row
    remember
    :localized-label="myLabels"
    :row-style="rowstyle"
    @update="update"
  >

    <vue-excel-column
      field="id"
      readonly
      :to-text="idTextCallback"
      label="#"
      key-field
    />
    <vue-excel-column
      field="patentfamilieNr"
      label="PatentfamilienNr"
      :link="openHelper"
      width="70px"
    />
    <vue-excel-column field="ctZeichen" label="CTZeichen" />
    <vue-excel-column field="land" label="Land" width="50px" />
    <vue-excel-column field="frist" label="Frist" />
    <!--  type="date" -->
    <vue-excel-column field="termin" label="Termin" />
    <vue-excel-column field="kstArt" label="KstArt" width="50px" />
    <vue-excel-column
      field="terminbeschreibung"
      width="120px"
      label="Terminbeschreibung"
    />
    <vue-excel-column
      field="mayCost"
      label="GeschätzteKosten"
      width="70px"
      type="number"
    />
    <vue-excel-column
      field="status"
      label="Status"
      :options="['Offen', 'Erledigt', 'i.A.', 'i.A Rechnung', 'Dringend', '']"
    />
    <vue-excel-column
      field="freigabeSonstiges"
      label="FreigabeSonstiges"
      width="50px"
    />
    <vue-excel-column field="bemerkung" width="200px" label="Bemerkung" />
    <vue-excel-column field="orderedFrom" width="70px" label="BestelltVon" />
    <vue-excel-column field="orderedWhen" width="85px" label="BestelltAm" />
    <vue-excel-column
      field="realCost"
      label="TatsächlicheKosten"
      width="70px"
      type="number"
    />
    <vue-excel-column
      field="rechnungsnummerExtern"
      label="RechnungsnummerExtern"
      width="90px"
    />
    <vue-excel-column field="rechnungsnummerCt" label="RechnungsnummerIntern" />
    <vue-excel-column
      field="freigabeRechnung"
      width="70px"
      label="FreigabeRechnung"
    />
    <vue-excel-column
      field="freigabeDatum"
      width="85px"
      label="FreigabeDatum"
    />
    <vue-excel-column field="anFibu" width="70px" label="AnFibu" />
    <vue-excel-column field="kommentar" width="200px" label="Kommentar" />
    <vue-excel-column
      field="rueckstellung"
      width="200px"
      label="Rückstellung"
    />
    <vue-excel-column
      field="rueckstellungBetrag"
      label="Rückstellungsbetrag"
      type="number"
      width="60px"
    />
    <vue-excel-column field="kontrolle" label="Kontrolle" />
    <vue-excel-column field="abweichung" label="Abweichung" />
  </vue-excel-editor>
```
And for the col status, I just made a select statement on MSSQL Studio and pasted all the values from status into the text file below. Hope you can figure something out with that.
I checked about the line endings and they all have CR LF. Do you think that is the culprit?

[AllStatus.txt](https://github.com/cscan/vue-excel-editor/files/4812725/AllStatus.txt)

Edit: Wrong table...oops

**Comment by cscan** [comment]
The sorting code is very simple

```
    sort (n, pos) {
      this.processing = true
      const colPos = typeof pos === 'undefined' ? this.columnFilterRef.colPos : pos
      const fieldName = this.fields[colPos].name
      const type = this.fields[colPos].type
      setTimeout(() => {
        if (type === 'number')
          this.value.sort((a, b) => {
            if (Number(a[fieldName]) > Number(b[fieldName])) return n
            if (Number(a[fieldName]) < Number(b[fieldName])) return -n
            return 0
          })
        else
          this.value.sort((a, b) => {
            if (a[fieldName] > b[fieldName]) return n
            if (a[fieldName] < b[fieldName]) return -n
            return 0
          })
        this.sortPos = colPos
        this.sortDir = n
        this.$forceUpdate()
        this.processing = false
      }, 0)
    },
```

you may process the following by your code and see whether you got the same result. I strongly believe it is due to your content
```
          this.value.sort((a, b) => {
            if (a[fieldName] > b[fieldName]) return n
            if (a[fieldName] < b[fieldName]) return -n
            return 0
          })
```

**Comment by cscan** [comment]
Could you please specified the type = "select" in status column, it should not relate to your problem, but I cannot ensure any unexpected if you did not specify the type.

```
    <vue-excel-column
      field="status"
      label="Status"
      type="select"
      :options="['Offen', 'Erledigt', 'i.A.', 'i.A Rechnung', 'Dringend', '']"
    />
```

**Comment by getraid** [comment]
Like you said, I entered the type, but it also didn't matter.
I tried the sorting as well and I don't get it. It matches with the table 1:1.

Honestly no clue what my content could be doing that horrendously wrong, but anyway.
Since there are other important pages to be created first (on my end), I'll maybe look into the issue again at a later point.
Or I try to resolve it in another way (don't know yet).
Thank you in any case for taking time to listen to me 
![sorting](https://user-images.githubusercontent.com/32432718/85284828-1fcc6280-b490-11ea-8777-874de77a8afa.PNG)

**Comment by getraid** [comment]
hey, I just looked at the code again and asked myself, why do you compare strings like that. I searched a bit and turns out that String.localeCompare() is my solution.
I found this code snippet [here](https://stackoverflow.com/questions/51165/how-to-sort-strings-in-javascript/51169#51169)
and I tried it and it worked locally.
![sortingsolution](https://user-images.githubusercontent.com/32432718/85295006-9cb30880-b49f-11ea-90a0-af0ce5286e09.PNG)

**Comment by cscan** [comment]
Good info indeed.
Anyway, I will allow user to assign the custom sorting function via column prop in next version

**Comment by cscan** [comment]
Please try v1.3.71
