### ISSUE TITLE
Exec-Command deprecated

### ISSUE THREAD

**Issue by ste-gr** [cscan/vue-excel-editor#90]
https://github.com/cscan/vue-excel-editor/blob/088d7ff5cfdca8b0d40394f53f3b6db6e0381ebe/src/VueExcelFilter.vue#L88
https://github.com/cscan/vue-excel-editor/blob/088d7ff5cfdca8b0d40394f53f3b6db6e0381ebe/src/VueExcelFilter.vue#L124

The `document.execCommand` is deprecated as you could see here: [MDN - Document.execCommand()](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand).

So I would suggest following change:
Line 88 and 124: `this.selectAll(this.cell)`

New method:
```
selectAll(node) {
  var selection = window.getSelection();
  if (selection) {
    var range = document.createRange();
    range.selectNodeContents(node);
    selection.removeAllRanges();
    selection.addRange(range);
  }
},
```

**Comment by cscan** [comment]
Changed. See v.1.4.2
