### ISSUE TITLE
How to display error on cell after data filled into table ?

### ISSUE THREAD

**Issue by ghost** [cscan/vue-excel-editor#92]
Hi all,

Currently, `validate` is only triggered after change value of cell. But I want to mark cell is invalid immediately after data loaded into table ? How can I do that? 

Thanks for helps !

**Comment by cscan** [comment]
You may try to set the errmsg variable, something like this:

```js
const fieldname = 'gender'
const id = 'id-' + rec[0].$id + '-' + fieldname
this.$refs.grid.errmsg[id] = 'Error Here'
this.$refs.grid.$forceUpdate()
```
