### ISSUE TITLE
1.4.2 version, mouse scroll stopped working

### ISSUE THREAD

**Issue by sergeyayz** [cscan/vue-excel-editor#93]
Hello,

I have updated to new version 1.4.2 and mouse scroll stopped working when scrolling through excel items in the spreadsheet the screen doesn't go down. Even if i use keyboard i cant get to the last items, if i update to older version 1.3.94, scrolling works, i have been able to reproduce this issue with two different data sets.

Testing browser Chrome 90.0
Vue 2.6.12

**Comment by cscan** [comment]
I added the capturing of the event mousewheel within the grid area, you may set no-mouse-scroll to disable it
