### ISSUE TITLE
Negative numbers in Ids when scrolling down with plugin's scrollbar

### ISSUE THREAD

**Issue by sergeyayz** [cscan/vue-excel-editor#94]
Hello,

When scrolling with vue-excel-editor's vertical scrollbar spreadsheet goes into negative ids and the same error goes into the concole hundreds of times every time I scroll (because recPos const becomes negative ): 
Uncaught TypeError: Cannot read property 'name' of undefined
    at eval (VueExcelEditor.vue?d21b:1126)
    at Array.map (<anonymous>)
    at VueComponent.vsbMouseMove (VueExcelEditor.vue?d21b:1126)
eval @ VueExcelEditor.vue?d21b:1127
vsbMouseMove @ VueExcelEditor.vue?d21b:1127

Was able to reproduce in 
 versions 1.4.20, 1.3.94.
Testing browser Chrome 90.0, Firefox 88.0
Vue 2.6.12

![IMG_20210602_105857_254](https://user-images.githubusercontent.com/58885080/120445803-a7ee0400-c391-11eb-81cb-8510e1267fa1.jpg)

**Comment by cscan** [comment]
I could not reproduce the same problem, could you show me your html tag?

**Comment by sergeyayz** [comment]
<vue-excel-editor
      ref="excelRef"
      v-model="excelData.data"
      @select="rowSelect"
      @update="onCellUpdate($event)"
      @cell-focus="onCellFocus($event)"
      height="82.9vh"
      no-header-edit
      filter-row
      autocomplete
      :page="100"
    >

**Comment by sergeyayz** [comment]
The negative numbers appear only when i use apps vertical scroll bar to scroll down.

**Comment by cscan** [comment]
How about you remove :page="100" ?
