### ISSUE TITLE
Cannot display nested field data

### ISSUE THREAD

**Issue by mainstreetmark** [cscan/vue-excel-editor#95]
Hello!

I have nested data from the server:

```json
[
  {
    "id": 10,
    "name": "Frequency",
    "symbol": "HZ",
    "props": {
      "range_high": "120",
      "range_low": "55",
      "decimals": "3"
    }
}
]
```
As you can see, the data is unflattened, and I would like to keep it that way for easier saving back up to the server.  But:

```html
<vue-excel-column field="props.range-high" label="Range High">
```
...doesn't render "120" as expected.  It just renders empty.

The to-value/to-text functions even receive "undefined", so i cannot handle it on the fly.

**Comment by cscan** [comment]
I come with an idea that you may implement a get set variable in your data:

```js
  {
    "id": 10,
    "name": "Frequency",
    "symbol": "HZ",
    "newvariable": {
         get () {.....},
         set () {......}
    }
    "props": {
      "range_high": "120",
      "range_low": "55",
      "decimals": "3"
    }
```

Please let me know if it works
