### ISSUE TITLE
Support for vue 3

### ISSUE THREAD

**Issue by einord** [cscan/vue-excel-editor#96]
Is there any plan for support/road map for vue 3?

**Comment by cscan** [comment]
Wow, no idea or plan about vue 3. Let me look into it during holiday

**Comment by larsderidder** [comment]
Very curious about this one as well! I start all new projects with Vue3, so would be great if this could support Vue3 as well.

**Comment by reinerBa** [comment]
I tried to migrate for the last hours. I can display the cells and the prop-value changes but not the content in the table... 
https://github.com/reinerBa/vue-excel-editor/commit/868296fcc75e92a9eee8021d93ef608b6adcdd4f

Which migration strategy do you prefer @cscan , i seems to be not easy to use one codebase for v2 and v3.

**Comment by reinerBa** [comment]
I used this codebase for try and error https://github.com/reinerBa/vue-exce-editor-vue3migration-demo
Do you plan to write a demo or examples?

**Comment by ryhn** [comment]
Hi, 
I think if this library doesn't support vue3 it would be wasted :disappointed: except vue2 users :smiling_face_with_tear:

**Comment by mickey-bimlive** [comment]
I'm very interested in getting a version of Vue Excel Editor for Vue 3. Based on my experiences with migrating a Vue 2 project to Vue 3, I agree that it would probably require a fork of the code base, one for Vue 2, another one for Vue 3. Alternatively the differences could maybe be controlled through v-ifs. The differences are small, but could affect a lot of code (like changing ":value" to ":modelValue" and similar little changes in syntax).

**Comment by edson-gaspar** [comment]
I would like to suggest use "vue-demi" to write universal vue libraries for vue 2 and vue 3 compatible.
ref:
https://github.com/vueuse/vue-demi

**Comment by edutucci** [comment]
Guys I have a project in quasar with vue-excel-editor components files.
I have changed small code part to work in vue 3.
We need copy the files from my project to here.
Sorry if was too bad with a quasar project. But I am translating small code vue2 to vue3.
I just want to help this project.

https://github.com/edutucci/quasar-vue-excel-editor

Files to copy here
components/VueExcelEditor

**Comment by cscan** [comment]
Thanks @edutucci

**Comment by cscan** [comment]
Hi all, I have drafted one for Vue3: https://github.com/cscan/vue3-excel-editor
Thanks for @edutucci again

**Comment by eskiesirius** [comment]
> Hi all, I have drafted one for Vue3: https://github.com/cscan/vue3-excel-editor Thanks for @edutucci again

Is this working good?
