### ISSUE TITLE
Mass import Excel data feature

### ISSUE THREAD

**Issue by ftahery-teleo** [cscan/vue-excel-editor#98]
Thank you for such a great library.
The last feature in the feature list says "Mass import Excel data". Can you explain what does this feature mean and how to import mass data?
Does it mean you can copy and paste multiple rows and columns and paste in the same format?

**Comment by cscan** [comment]
It is not through copy & paste. You could import the physical Excel file into your program through this component by using the web upload feature. The component will look at the column header defined in row 1 and records start from row 2. You can call doImport( ) method to achieve this.

**Comment by kio-by** [comment]
Is it planned to be able to import a file without the column header defined in row 1, or to be able to specify a header in the table import method itself, for example: this.$refs.grid.importTable(firstrow, secondrow)? 
Thx!

**Comment by cscan** [comment]
This is required by the XLSX component. I am using its sheet_to_row_object_array function. You could refer to the function doImport( ) in VueExcelEditor and write your own import by cloning the project. the doImport function is quite long but most of the codes are validation related. If you ignore the validation, it is only dozen lines I think.
