### ISSUE TITLE
Is it have drag to fill 

### ISSUE THREAD

**Issue by frogprincehe** [cscan/vue-excel-editor#99]
Hi, Is it have drag to fill column.,like Excel

**Comment by cscan** [comment]
Not yet implement this.

**Comment by frogprincehe** [comment]
Hi,cscan
 I have another questiuon.
I find Prop Component in vue-excel-editor has some function type Props, like "header-label" Props.
do you tell me, How to use these Props? I can`t find demo.
thanks!

**Comment by cscan** [comment]
Sorry, I can't catch what you want to do.

**Comment by cscan** [comment]
For the header-label, you may see the code in table th:

```html
    <div :class="{'filter-sign': columnFilter[p]}">
      <span :class="{'table-col-header': !noHeaderEdit}" v-html="headerLabel(item.label, item)"></span>
    </div>
```

the default headerLabel is defined as:

```js
    headerLabel: {
      type: Function,
      default (label) {
        return label
      }
    },
```

Which means I pass 2 arguments (label, item) into your function (if provided using prop), e.g.

```html
<vue-excel-editor header-label="myHeader" ...>
```

```js
function myHeader(label, item) {
   console.log(label, item) // For debugging
   switch(label) {
      case 'sku':
         return 'SKN'
      case 'descr':
         return 'DESCRIPTION'
   }
}
